# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBNhMhtKH3OJQp-Sd4JuhW2xhjks53-5
"""

# object id:id(object) and reference count : sys.getrefcount(object)
import sys
number:int=2
other_number=number
print(id(number)) # object id of number is a long integer
print(id(other_number)) # object id of other_number is the same as number
number+=1 # Not IN_PLACE
print(id(number)) # object id of number is a long integer
print(id(other_number)) # object id of other_number is not the same as number
print(number)
print(other_number)
print(sys.getrefcount(number))
print(sys.getrefcount(other_number))

#list references and objectid
alist:list[int]=['a','b','c','d','e','f']
aslice: list[int]=alist[2:4]
print(id(alist))
print(id(aslice))
print(id(alist[2]))
print(id(aslice[0]))
print(id(alist[3]))
print(id(aslice[1]))
print(alist)
print(aslice)
aslice[0]='x'
print(alist)
print(aslice)
print(id(alist[2]))
print(id(aslice[0]))

n=int(input("Enter the size of the list"))
a=[int(input("Enter the element")) for _ in range(0,n)]
b=a[:]
b[0]=1
print(id(a))
print(id(b))
print(a)
print(b)

stringy:str=input("Enter a string:")
stringzy:str=stringy
print(id(stringy)) # some long int memory address
print(id(stringzy))
stringzy="I am a different string object"
print(id(stringzy)) # some different long int memory address
print(stringy)
print(stringzy)

stringy:str=input("Enter a string:")
stringzy:str=stringy[:]
print(id(stringy))
print(id(stringzy))
stringzy="I am a different string object"
print(id(stringzy))
print(stringy)
print(stringzy)

l1=[1,2,3]
l2=l1
l3=[l1,l1,l1]
l1[0]=5
print(l1)
print(l3[0])
print(l1)
print(id(l1))
print(id(l2))
print(id(l3[0]))
print(id(l3[1]))
print(id(l3[2]))

l1=[1,2,3]
l2=l1
l3=[l1[:],l1[:],l1[:]]
l1[0]=5
print(l1)
print(l3[0])
print(l1)
print(id(l1))
print(id(l2))
print(id(l3[0]))
print(id(l3[1]))
print(id(l3[2]))

L1=[1,2,3]
L2=L1
L3=L1+[4] # seperate  copy of the L1 to which [4] is concatenated and the previous three are having references to the original objects
L1.append(5) # in-place appending of element 5 to the list
print("L1=",L1)
print("L2=",L2)
print("L3=",L3)
print("object id of L1:",id(L1))
print("object id of L2:",id(L2))
print("object id of L3:",id(L3))

A=[1,2]
B=list(A) # calling list(iterable) creates a new outer list while referencing the original nested objects
C=A
D=A[:]
B[1]=7
print("A=",A)
print("B=",B)
print("C=",C)
print("D=",D)
print(f"object id of A:{id(A)}")
print(f"object id of B:{id(B)}")
print(f"object id of C:{id(C)}")
print(f"object id of D:{id(D)}")

import sys
x=[[22],[33],[22],[33]]
x[0]=x[2]
x[1]=x[3]
print(id(x))
print(id(x[0]))  # long int memory address
print(id(x[1]))  # long int memory address
print(id(x[2]))  # long int memory address same as x[0]
print(id(x[3]))  # long int memory address same as x[1]
print(sys.getrefcount(x)) # 2
print(sys.getrefcount(x[0])) # 3
print(sys.getrefcount(x[1])) # 3
print(sys.getrefcount(x[2])) # 3
print(sys.getrefcount(x[3])) # 3

x=[[22],[33]]
print(id(x[0]),id(x[1]))
print(id(x[0][0]),id(x[1][0]))
x=x*2
print(x)
print(id(x[0]),id(x[1]),id(x[2]),id(x[3]))
print(id(x[0][0]),id(x[1][0]),id(x[2][0]),id(x[3][0]))
x[0][0]=1
print(x)
print(id(x[0]),id(x[1]),id(x[2]),id(x[3]))
print(id(x[0][0]),id(x[1][0]),id(x[2][0]),id(x[3][0]))
x[0]=[1] #wherever there is assignment there may be the change
print(x)
print(id(x[0]),id(x[1]),id(x[2]),id(x[3]))

a=[22]
print(id(a))
print(id(a[0]))
b=[33]
print(id(b))
print(id(b[0]))
x=[a,b,a,b]
print(id(x))
print(id(x[0]),id(x[1]),id(x[2]),id(x[3]))
print(id(x[0][0]),id(x[1][0]),id(x[2][0]),id(x[3][0]))

x=[[22],[33],[22],[33]]
print(id(x[0]),id(x[1]),id(x[2]),id(x[3]))
print(id(x[0][0]),id(x[1][0]),id(x[2][0]),id(x[3][0]))

a=[[1,2,3],[4,5,6],[7,8,9]]
b=a[1:]
a[1][0]=100
b[0]=[10,11]
b[1][0]=99
print(a)
print(b)
print(id(a[0]),id(a[1]),id(a[2]))
print(id(b[0]),id(b[1]))
print(id(a[0][0]),id(a[1][0]),id(a[2][0]))
print(id(b[0][0]),id(b[1][0]))

a=[[1,2,3],[4,5,6],[7,8,9]]
b=a[1:]
print(id(b[0]))
print(id(a[1]))
# Slicing will just make one new list
a:list[str]=['a','b','c']
b:list[str]="2316"
c:list[[str,int]]=[a,b,5]
d=c[:]
for x in d[1]:
        a.append(x)
        c[2]=c[2]+1
print(id(a))
print(id(b))
print(id(c))
print(id(d))
print(a)
print(b)
print(c)
print(d)
print(id(a[2]))
print(id(b[2]))
print(id(c[2]))
print(id(d[2]))
print(id(c[2]+1))